# Generated by Django 4.1.5 on 2023-01-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update date')),
                ('number', models.CharField(max_length=10, verbose_name='Order number')),
                ('ship_from', models.CharField(max_length=10, verbose_name='Shipped from location')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Order status')),
                ('iteration', models.SmallIntegerField(default=1, verbose_name='Order processing iteration number')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update date')),
                ('uid', models.CharField(max_length=20, verbose_name='Item uniques id, T&T code')),
                ('validity', models.SmallIntegerField(default=0, verbose_name='Item verification status')),
                ('uom', models.CharField(db_index=True, default='MC', max_length=10, verbose_name='Item Unit of measure')),
                ('iteration', models.SmallIntegerField(default=1, verbose_name='Item processing iteration number')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hub_api.order')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
