# Generated by Django 4.1.5 on 2023-04-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mirusers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='downloadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloadedBy', to=settings.AUTH_USER_MODEL, verbose_name='Downloaded by'),
        ),
        migrations.AddField(
            model_name='order',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirusers.hub', verbose_name='Shipped from location'),
        ),
        migrations.AddField(
            model_name='order',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='item',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sUSNSet', to='hub_api.composition'),
        ),
        migrations.AddField(
            model_name='composition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sPositionSet', to='hub_api.order'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order', 'saleType')},
        ),
    ]
