# Generated by Django 4.1.6 on 2023-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerOrderNumber',
            field=models.CharField(default='x', max_length=10, verbose_name='Customer Order number'),
        ),
    ]
