# Generated by Django 4.1.5 on 2023-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=25)),
                ('traceability', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='productCategory',
            field=models.CharField(max_length=3, verbose_name='Product category'),
        ),
    ]
