# Generated by Django 4.1.5 on 2023-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_api', '0003_productcategory_alter_order_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deletion status'),
        ),
    ]
