# Generated by Django 4.1.6 on 2023-11-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_api', '0003_alter_order_customerordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csValidityStatus',
            field=models.BooleanField(default=None, null=True, verbose_name='Customer Service validation status'),
        ),
    ]
