# Generated by Django 4.1.6 on 2023-11-05 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub_api', '0004_order_csvaliditystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cs1CReadinessStatus',
            field=models.BooleanField(default=False, verbose_name='Customer Service 1C readiness status '),
        ),
        migrations.AddField(
            model_name='order',
            name='csDownloadStatus',
            field=models.BooleanField(default=False, verbose_name='Customer Service download status'),
        ),
        migrations.AddField(
            model_name='order',
            name='csDownloadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer Service downloaded by'),
        ),
    ]
