# Generated by Django 4.1.6 on 2023-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_api', '0006_order_cs1cprocessingstatus_order_cs1cunloadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csFDSOfile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='FDSO file'),
        ),
        migrations.AddField(
            model_name='order',
            name='csFDSOfileNumber',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='FDSO file number'),
        ),
    ]
