# Generated by Django 4.1.5 on 2023-06-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('participantId', models.CharField(max_length=10)),
                ('productionLineId', models.CharField(max_length=10)),
                ('productionOrderId', models.CharField(max_length=20)),
                ('sku', models.PositiveIntegerField()),
                ('batch', models.CharField(max_length=10)),
                ('uuid', models.UUIDField(db_index=True)),
                ('updatedBy', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Aggregation',
                'verbose_name_plural': 'Aggregations',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unitSerialNumber', models.CharField(db_index=True, max_length=70)),
                ('aggregatedItemsCount', models.PositiveSmallIntegerField()),
                ('aggregationType', models.CharField(default='AGGREGATION', max_length=15)),
                ('aggregationUnitCapacity', models.PositiveSmallIntegerField()),
                ('uuid', models.UUIDField(db_index=True)),
                ('aggregation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aggregationUnits', to='ext_tnt.aggregation')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('unitSerialNumber', models.CharField(db_index=True, max_length=70)),
                ('uuid', models.UUIDField(db_index=True)),
                ('aggregation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ext_tnt.aggregation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sntins', to='ext_tnt.unit')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
