# Generated by Django 4.1.5 on 2023-03-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='erpname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Hub name in ERP'),
        ),
    ]
