# Generated by Django 4.1.6 on 2023-10-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('gtd', models.CharField(max_length=50, verbose_name='Customs declaration number')),
                ('guid', models.UUIDField(unique=True, verbose_name='Unique GTD ids')),
            ],
            options={
                'verbose_name': 'GTD',
                'verbose_name_plural': 'GTDs',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('sku', models.PositiveIntegerField(db_index=True, verbose_name='SKU number')),
                ('gtd', models.ManyToManyField(related_name='items', to='hub_gtd.gtd', verbose_name='Customs declaration number')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('tuid', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='Tracking code')),
                ('gtd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub_gtd.gtd', verbose_name='Customs declaration number')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuids', to='hub_gtd.sku', verbose_name='SKU number')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
